<template>
  <div
    class="bg-white h-full fixed left-0 top-0 z-20 shadow-lg transition-all duration-200 ease-in flex flex-col"
    :class="{
      'w-16': is_collapsed,
      'w-56': !is_collapsed
    }"
  >
    <div class="h-16 text-center flex flex-col justify-center font-medium text-xl">
      <div :class="{
          hidden: is_collapsed
          }" class="pr-12">
        <template v-if='show_text'>
          <span class="text-indigo-600" v-if='show_text'>IMsight</span>
          Logo
        </template>
      </div>
      <div 
        class='rounded bg-indigo-200 mx-auto flex flex-row items-center h-12 w-12 justify-center'
        :class="{
          hidden: !is_collapsed
        }">
        <p class="m-0 text-indigo-600 leading-relaxed">IM</p>
      </div>
    </div>
    <div class="flex flex-col flex-grow">
      <div class="flex flex-col pt-6 flex-grow-0">
        <div
          @click="navigateTo(item)"
          :key="item.meta.label"
          class="nav-link"
          :class="{
            selected: linkIsCurrentLink(item)
          }"
          v-for="item in items"
        >
          <div
            :class="{
              selected: linkIsCurrentLink(item),
              'border-indigo-600': linkIsCurrentLink(item)
              }"
              :title="is_collapsed ? item.meta.label : ''"
            class="py-4 border-l-4 border-transparent text-base flex flex-row items-center cursor-pointer hover:text-gray-700 hover:bg-indigo-100"
          >
            <i :class="item.meta.icon" class="h-6 leading-6 text-lg pl-4 pr-2 text-gray-500"></i>
            <span
              v-if="show_text"
            >
              {{ item.meta.label }}
            </span>
          </div>
        </div>
      </div>
      <div
        class="hover:bg-gray-200 mt-auto py-6 h-10 border-t border-grey-500 text-sm flex flex-row w-full items-center justify-center cursor-pointer hover:text-gray-700"
        @click="collapseSideBar()"
      >
        <div class="flex flex-row select-none">
          <div class="flex flex-row items-center text-base w-full" :class="is_collapsed ? 'justify-center' : ''">
            <span class="fas fa-angle-double-left text-gray-600 rotate-initial-cw" :class="is_collapsed ? 'rotate-0-cw' : 'rotate-180-cw'"></span>
            <span class="pl-2 text-gray-600 overflow-hidden" v-if='show_text'>Collapse sidebar</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { getProfile } from "../utils/auth";
import { routes } from "@/utils/routes";
import SideNavMixin from "@/mixin/SideNav.mixin.js";

export default {
  name: "side-nav",
  mixins: [SideNavMixin],
  mounted() {},
  data: () => ({
    value: 0,
    item: 0,
    user: null,
    mini_variant: false,
    selected_action: {},
    user_actions: [
      {
        name: "Profilo",
        icon: "fas fa-user",
        path: "profile"
      },
      {
        name: "Impostazioni",
        icon: "fas fa-cog",
        path: "settings"
      },
      {
        name: "Logout",
        icon: "fas fa-sign-out-alt",
        path: "logout"
      }
    ],
    items: [],
  }),
  beforeMount() {
    this.user = getProfile();

    this.items = routes[1].children
      .filter(route => {
        // Only routes with the meta.label have to be present
        // in the SideNav
        return route.meta && route.meta.label != undefined;
      })
      .filter(route => {
        if (route.meta.roles) {
          let userRole = this.user.role.code.toLowerCase();

          return route.meta.roles.indexOf(userRole) != -1;
        }

        return true;
      });
  },
  methods: {
    doUserAction(action) {
      this.$router.push(action.path);
    },
    navigateTo(link) {
      // Don't navigate to same route or root route
      if (
        link.path != this.$route.name &&
        link.path != this.$route.redirectedFrom
      ) {
        this.$router.push(link.path);
      }
    },
    linkIsCurrentLink(link) {
      return this.$route.matched.map(l => l.name).indexOf(link.name) != -1;
    },
  },
  computed: {
    currentPath() {
      return this.$router.name;
    }
  }
};
</script>

<style>

/* ----------------------------------------------
 * Generated by Animista on 2020-3-16 10:24:13
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-90-cw
 * ----------------------------------------
*/

.rotate-initial-cw {
  transition: all 0.35s 0.10s;
  transform: rotate(180deg);
}

.rotate-0-cw {
  transform: rotate(180deg);
}

.rotate-180-cw {
  transform: rotate(0deg);
}
</style>
